# Generated by Django 3.2.9 on 2021-12-08 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('self_report', '0002_alter_attitudeform_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttitudeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('attitude_01_01', models.CharField(max_length=200)),
                ('attitude_01_02', models.CharField(max_length=200)),
                ('attitude_02_01', models.CharField(max_length=200)),
                ('attitude_02_02', models.CharField(max_length=200)),
                ('attitude_02_03', models.CharField(max_length=200)),
                ('attitude_02_04', models.CharField(max_length=200)),
                ('attitude_03_01', models.CharField(max_length=200)),
                ('attitude_03_02', models.CharField(max_length=200)),
                ('attitude_03_03', models.CharField(max_length=200)),
                ('attitude_04_01', models.CharField(max_length=200)),
                ('attitude_04_02', models.CharField(max_length=200)),
                ('attitude_04_03', models.CharField(max_length=200)),
                ('attitude_04_04', models.CharField(max_length=200)),
                ('attitude_05_01', models.CharField(max_length=200)),
                ('attitude_05_02', models.CharField(max_length=200)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='foreign_key')),
            ],
        ),
        migrations.DeleteModel(
            name='AttitudeForm',
        ),
    ]
