# Generated by Django 3.2.9 on 2021-12-10 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('self_report', '0008_schedulemodel_schedule_04_02'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('report_01_01', models.CharField(max_length=200)),
                ('report_01_02', models.CharField(max_length=200)),
                ('report_02_01', models.CharField(max_length=200)),
                ('report_02_02', models.CharField(max_length=200)),
                ('report_03_01', models.CharField(max_length=200)),
                ('report_03_02', models.CharField(max_length=200)),
                ('report_04_01', models.CharField(max_length=200, null=True)),
                ('report_04_02', models.CharField(max_length=200, null=True)),
                ('report_05_01', models.CharField(max_length=200, null=True)),
                ('report_05_02', models.CharField(max_length=200, null=True)),
                ('report_06_01', models.CharField(max_length=200, null=True)),
                ('report_06_02', models.CharField(max_length=200, null=True)),
                ('report_07_01', models.CharField(max_length=200, null=True)),
                ('report_07_02', models.CharField(max_length=200, null=True)),
                ('report_08_01', models.CharField(max_length=200, null=True)),
                ('report_09_01', models.CharField(max_length=200, null=True)),
                ('report_10_01', models.CharField(max_length=200, null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='foreign_key')),
            ],
        ),
    ]
