# Generated by Django 3.2.9 on 2021-12-12 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('self_report', '0010_auto_20211212_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportETCModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('report_etc_01_01', models.CharField(max_length=200)),
                ('report_etc_02_01', models.CharField(max_length=200)),
                ('report_etc_03_01', models.CharField(max_length=200)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='foreign_key')),
            ],
        ),
    ]
