# Generated by Django 3.2.9 on 2021-12-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_report', '0009_reportmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmodel',
            name='report_08_01',
        ),
        migrations.RemoveField(
            model_name='reportmodel',
            name='report_09_01',
        ),
        migrations.RemoveField(
            model_name='reportmodel',
            name='report_10_01',
        ),
    ]
