# Generated by Django 3.2.9 on 2021-12-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttitudeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('attitude_01_01', models.CharField(max_length=200)),
                ('attitude_01_02', models.CharField(max_length=200)),
                ('attitude_02_01', models.CharField(max_length=200)),
                ('attitude_02_02', models.CharField(max_length=200)),
                ('attitude_02_03', models.CharField(max_length=200)),
                ('attitude_02_04', models.CharField(max_length=200)),
                ('attitude_03_01', models.CharField(max_length=200)),
                ('attitude_03_02', models.CharField(max_length=200)),
                ('attitude_03_03', models.CharField(max_length=200)),
                ('attitude_04_01', models.CharField(max_length=200)),
                ('attitude_04_02', models.CharField(max_length=200)),
                ('attitude_04_03', models.CharField(max_length=200)),
                ('attitude_04_04', models.CharField(max_length=200)),
                ('attitude_05_01', models.CharField(max_length=200)),
                ('attitude_05_02', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=200)),
            ],
        ),
    ]
