# Generated by Django 3.2.9 on 2021-12-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_report', '0007_schedulemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='schedule_04_02',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
