# Generated by Django 3.2.9 on 2021-12-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitudeform',
            name='post_id',
            field=models.IntegerField(),
        ),
    ]
