# Generated by Django 3.2.9 on 2021-12-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_report', '0003_auto_20211208_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitudemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
